/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "The Rise Of Physical AI and Humanoid Robotics",
  "tagline": "AI Systems in the Physical World. Embodied Intelligence.",
  "favicon": "img/logo.png",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "url": "https://imsanghaar.github.io",
  "baseUrl": "/",
  "organizationName": "imsanghaar",
  "projectName": "my-book",
  "onBrokenLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts"
        },
        "blog": {
          "showReadingTime": true
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "colorMode": {
      "defaultMode": "dark",
      "respectPrefersColorScheme": false,
      "disableSwitch": false
    },
    "navbar": {
      "title": "The Rise of Physical AI and Humanoid Robotics",
      "logo": {
        "alt": "AI Native Logo",
        "src": "img/logo.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Book"
        },
        {
          "type": "html",
          "position": "right",
          "value": "\n            <span title=\"This Book is Under Developemnt By AI Agents\" style=\"cursor: help; display: flex; align-items: center;\">\n              <span style=\"background-color: yellow; border-radius: 50%; width: 12px; height: 12px; display: inline-block; margin-right: 5px;\"></span>\n              Under Development\n            </span>\n          "
        },
        {
          "href": "https://github.com/imsanghaar",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "LEARN",
          "items": [
            {
              "label": "Start Your Journey",
              "to": "/docs/introduction/"
            },
            {
              "label": "My Work",
              "href": "https://sanghaar.vercel.app/"
            },
            {
              "label": "WhatsApp",
              "href": "https://wa.me/923441323835"
            }
          ]
        },
        {
          "title": "COMMUNITY",
          "items": [
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/imam-sanghaar-chandio-96780b274/"
            },
            {
              "label": "Instagram",
              "href": "https://www.instagram.com/imsanghaar/"
            },
            {
              "label": "Facebook",
              "href": "https://www.facebook.com/profile.php?id=61556981875577"
            }
          ]
        },
        {
          "title": "RESOURCES",
          "items": [
            {
              "label": "GitHub Profile",
              "href": "https://github.com/imsanghaar"
            },
            {
              "label": "Projects",
              "href": "https://github.com/imsanghaar?tab=repositories"
            }
          ]
        },
        {
          "title": "ABOUT",
          "items": [
            {
              "label": "About Author",
              "href": "https://sanghaar.vercel.app/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Imam Sanghaar • AI Developed Book Series • Free & Open Source"
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
