openapi: 3.0.0
info:
  title: RAG Chatbot API
  version: 1.0.0
  description: API for the RAG Chatbot that answers questions about a book.

paths:
  /query:
    post:
      summary: Submit a user query to the chatbot.
      operationId: queryChatbot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserQuery'
      responses:
        '200':
          description: Successful response with chatbot answer.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatbotResponse'
        '400':
          description: Bad Request - Invalid input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /update_index: # Internal endpoint for scheduled updates
    post:
      summary: Trigger an update of the book content index.
      operationId: updateBookIndex
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source_type:
                  type: string
                  enum: [book_content, metadata]
                  description: The type of content to update.
              required:
                - source_type
      responses:
        '200':
          description: Index update successful.
        '400':
          description: Bad Request - Invalid input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    UserQuery:
      type: object
      properties:
        query_text:
          type: string
          description: The natural language question from the user.
          example: "What is the main thesis of Chapter 3?"
        session_id:
          type: string
          description: Identifier for the current conversation session (optional).
          example: "session_abc123"
        timestamp:
          type: string
          format: date-time
          description: When the query was made.
      required:
        - query_text

    ChatbotResponse:
      type: object
      properties:
        response_text:
          type: string
          description: The generated answer from the chatbot.
          example: "The main thesis of Chapter 3 discusses..."
        explanation:
          type: string
          description: Elaboration or context for the answer.
          example: "This is based on the introductory paragraphs of Chapter 3."
        source:
          type: string
          description: Reference to the book content (e.g., Chapter title and section name).
          example: "Chapter 3: Introduction to AI"
        confidence_score:
          type: number
          format: float
          description: A measure of the chatbot's confidence in the answer (optional).
          example: 0.95
        timestamp:
          type: string
          format: date-time
          description: When the response was generated.
      required:
        - response_text
        - explanation
        - source

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: A description of the error.
        code:
          type: integer
          description: An error code.
      required:
        - message
        - code
